### ISSUE TITLE
Optionalize the fallback for local authentication

### ISSUE THREAD

**Issue by ctgraham** [shemgp/ojs_ldap_plugin#5]
Depending on the configuration, we may want to call the local authentication before the LDAP call (e.g. most accounts are local), after the LDAP call (e.g. most accounts are LDAP), or never (e.g. all accounts must be LDAP).

We can add this as an option in the settings form.

**Comment by ctgraham** [comment]
https://forum.pkp.sfu.ca/t/ojs3-ldap-plugin/27915/46?u=ctgraham
> Would it be possible to make the LDAP Self Service field optional as well? If I set it to our LDAP self-service URL, then users with local non-LDAP accounts won’t be able to reset their passwords.

**Comment by shemgp** [comment]
I've pushed fixes to the master that "should" fix these problems. However, I'm waiting for your fix to #8 to fully test it. Please check. Thank you.

**Comment by shemgp** [comment]
@ctgraham  I've tested my latest pushes and LDAP call ordering and self service as optional is working on my side. Can you test? Thanks.

**Comment by ctgraham** [comment]
Calling `parent::signIn()` will not return to this function.
https://github.com/shemgp/ojs_ldap_plugin/blob/099d13dd114ab7ae6a7bb3b04bcddc7a267fdba5/pages/LDAPHandler.inc.php#L127-L129

It works really well at the end of the function, because we will run exactly the core OJS signin code after trying LDAP, but if tried early in the process, the code will ultimately either redirect the user, or display the login form, not return processing to our caller:
https://github.com/pkp/pkp-lib/blob/27eeff555bdcfa6da9f787d259184b1cfacff025/pages/login/LoginHandler.inc.php#L87-L133

**Comment by ctgraham** [comment]
Not a functional critique, but best practice is to define values like "before", "never", and "after" as constants rather than as quoted strings in the code:
https://github.com/shemgp/ojs_ldap_plugin/blob/099d13dd114ab7ae6a7bb3b04bcddc7a267fdba5/pages/LDAPHandler.inc.php#L128

See the OrcidProfile plugin as an example:
https://github.com/pkp/orcidProfile/blob/75b0d5086706c06398f49a8f163720ae141631d8/OrcidProfilePlugin.inc.php#L19-L33

Also, note that you don't need to check if the value is equal to something and not equal to something else.  The second and third conditions are redundant:
```
		if ($ldapLocalLoginOrder == "before" && $ldapLocalLoginOrder != "never" && $ldapLocalLoginOrder != "")
```
You may have been concerned about the ambiguity of PHP's `==` operator.  The best formulation of this would look like:
```
define('LDAPAUTH_LOCAL_BEFORE', 'before');
```
and
```
		if ($ldapLocalLoginOrder === LDAPAUTH_LOCAL_BEFORE) {
```

**Comment by shemgp** [comment]
Thanks for the input. Made the necessary changes. Please look and test. Thanks.
